debug: true
debug_console: false
logging:
  level: DEBUG
brainstate_location: brainstate.json
plugin_dir: plugins/
plugins:
  - shipit
  - brew
  - deletemessages
  - ping
  - notebook
plugin_config:
  notebook:
    file: notebook.docx
    append: false
api_token: 'foobar'
