debug: true
debug_console: false
logging:
  level: DEBUG
brainstate_location: brainstate.json
plugin_dir: plugins/
plugins:
  - shipit
  - brew
  - deletemessages
  - ping
  - hello
  - thequestion
  - notebook
api_token: 'foobar'
